# Site settings
title: hqglichao's 博客
email: huangqinggai@126.com
author: Qinggai Huang
github: https://github.com/hqglichao
description: 我的博客，孤芳自赏
meta_description: 黄庆概;个人博客;莫等闲，白了少年头，空悲切。
# motto: 坚持一件事情，可能是今年，可能是明年，可能就是有生之年。
banner: 书山有路勤为径，学海无涯苦作。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: hqglichao

# Build settings
markdown: kramdown

url: "https:\\hqglichao.github.io"
plugins:
  - jekyll-sitemap

baidu_analysis: d45e57342a97903c697716b06f129b82
